version: '3'
  
networks:
  inception_network:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb:final
    env_file: .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
        DB_USERNAME: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception_network
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx:final
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: on-failure 

  wordpress:
    container_name: wordpress
    image: wordpress:final
    env_file: .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
          DB_NAME: ${DB_NAME}
          DB_USERNAME: ${DB_USER}
          DB_PASSWORD: ${DB_PASSWORD}
          DOMAIN_NAME: ${DOMAIN_NAME}
          WP_TITLE: ${WP_TITLE}
          WP_ADMIN_USERNAME: ${WP_ADMIN_USERNAME}
          WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
          WP_ADMIN_MAIL: ${WP_ADMIN_MAIL}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    expose:
      - "9000"
    networks:
      - inception_network
    restart: on-failure

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/chmadran/data/mysql
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/chmadran/data/wordpress
      o: bind

  
